export const SWEETNOTHINGS = {};

SWEETNOTHINGS.ID = "SweetNothings";
SWEETNOTHINGS.MODULE_PATH = `modules/${SWEETNOTHINGS.ID}/`;
SWEETNOTHINGS.TEMPLATE_PATH = `${SWEETNOTHINGS.MODULE_PATH}/templates/`;
SWEETNOTHINGS.TEMPLATES = {
    DIALOG: `${SWEETNOTHINGS.TEMPLATE_PATH}sweetNothingsDialog.hbs`
}